# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-json
  - id: check-toml
  - id: check-added-large-files

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.9.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --preserve-quotes, --indent, '2']

- repo: local
  hooks:
  - id: pyupgrade
    name: pyupgrade
    entry: poetry run pyupgrade
    language: system
    types: [python]
    args: [--py310-plus]

  - id: black
    name: black
    entry: poetry run black
    language: system
    types: [python]

  - id: autoflake
    name: autoflake
    entry: poetry run autoflake
    language: system
    types: [python]
    args: [--in-place]

  - id: isort
    name: isort
    entry: poetry run isort
    language: system
    types: [python]

  - id: flake8
    name: flake8
    entry: poetry run flake8
    language: system
    types: [python]
    exclude: ^(tests|cetd|textrank)/

  - id: mypy
    name: mypy
    entry: poetry run mypy
    language: system
    types: [python]
    exclude: ^(tests|cetd|textrank)/

  - id: bandit
    name: bandit
    entry: poetry run bandit
    language: system
    types: [python]
    args: [-c, pyproject.toml]
