mongo_db_data_example = {
    "status": "success",
    "message": "성공",
    "ServerDateTime": "2021-07-01 10:00:00",
    "data": {
        "orderNo": "202107010001",
        "status": "ACCEPTED",
        "statusReason": "ACCEPTED_00",
        "serviceType": "DELIVERY",
        "deliveryType": "DELIVERY",
        "deliveryCarryType": "COMMON",
        "reservation": false,
        "payAmount": 10000,
        "discountAmount": 0,
        "orderAmount": 10000,
        "menuDiscountAmount": 0,
        "txAmount": 10000,
        "disposalbleCupOrderAmount": 0,
        "occurredPoint": 0,
        "orderDatetime": "2021-07-01 10:00:00",
        "acceptDatetime": "2021-07-01 10:00:00",
        "arriveDatetime": "2021-07-01 10:00:00",
        "charge": {},
        "shop": {},
        "items": [],
        "payments": [],
        "discounts": [],
        "orderer": {},
        "memos": [],
        "card": false,
        "cardReceipt": false,
        "cash": false,
        "adCampaign": {},
        "deliveryAgencyType": "STORE",
        "regionalCode": "41",
        "delivery": {},
        "cancellable": false,
        "familyOrder": {},
        "isFamilyOrder": false,
        "isGroupOrder": false,
    },
}

json_data_example = {
    "orderNo": "202107010001",
    "orderStatus": "ACCEPTED",
    "orderDatetime": "2021-07-01 10:00:00",
    "orderPayMethod": {},
    "orderMemo": {},
    "orderStatusHistory": [],
    "delivery": {},
    "lineItems": [],
    "sellerSummary": {},
    "chargeLines": [],
}
